### ISSUE TITLE
Error in SCHEDULER function:[string "/scripts/misFaily/InitMisFaily.lua"]:500

### ISSUE THREAD

**Issue by xvx45** [Kalbuth/misFaily#10]
Arrive à toutes les unités environs 450 fois par heure réelle.
Non limité à GROUP_DYN_B_Center#001 mais sur toute unités spawnées

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

INFO    SCRIPTING: E:                BASE00000({[1]=Cannot GetCoordinate,[Group]={[LastTransmission]=146,[Takeoff]={[Air]=1,[Hot]=3,[Runway]=2,[Cold]=4,},[EnnemyPosition]={[WaypointAction]={[TurningPoint]=Turning Point,[FromParkingAreaHot]=From Parking Area Hot,[FromRunway]=From Runway,[Landing]=Landing,[FromParkingArea]=From Parking Area,[FlyoverPoint]=Fly Over Point,},[y]=19.49591255188,[z]=290658.0625,[x]=-2768.029296875,[WaypointAltType]={[RADIO]=RADIO,[BARO]=BARO,},[WaypointType]={[TurningPoint]=Turning Point,[TakeOff]=TakeOffParkingHot,[Land]=Land,[TakeOffParkingHot]=TakeOffParkingHot,[TakeOffParking]=TakeOffParking,},[ClassName]=COORDINATE,},[Mark]=3070,[Detection]={[current]=Detecting,[_FlareDetectedUnits]=false,[DetectedItemMax]=4,[DetectedItemCount]=1,[DetectionRun]=0,[DetectionCount]=1,[DetectedObjectsIdentified]={},[LocalGroup]=GROUP_DYN_B_Center#001,[DetectOptical]=true,[DetectVisual]=true,[AcceptRange]=5000,[_SmokeDetectedUnits]=false,[_SmokeDetectedZones]=false,[ClassName]=DETECTION_AREAS,[DetectionZoneRange]=500,[_FlareDetectedZones]=false,[_BoundDetectedZones]=false,},[LocalSet]={[Filter]={[Active]=false,},[FilterMeta]={[Categories]={[helicopter]=1,[ground]=2,[plane]=0,[ship]=3,},[Coalitions]={[neutral]=0,[blue]=2,[red]=1,},},[current]=Started,[ClassName]=SET_GROUP,},[Radio]={[Modulation]=0,[Power]=20,[SubtitleDuration]=0,[FileName]=l10n/DEFAULT/beaconsilent.ogg,[Positionable]={[Takeoff]={[Air]=1,[Hot]=3,[Runway]=2,[Cold]=4,},[GroupName]=RADIO_Center,[ClassName]=GROUP,},[Loop]=false,[ClassName]=RADIO,[Subtitle]=,[Frequency]=287100000,},[TargetZone]={[ScanData]={[Scenery]={},[Coalitions]={[1]=true,[2]=true,},[Units]={[table: 00000006224C0AD0]={[id_]=16911617,},[table: 00000006224C0640]={[id_]=16911105,},[table: 0000000623E6F4B0]={[id_]=16959489,},[table: 0000000632AABCF0]={[id_]=16958465,},[table: 00000006224C0900]={[id_]=16910337,},[table: 0000000632AABA60]={[id_]=16933889,},[table: 00000006224C0730]={[id_]=16911361,},[table: 0000000632AAB850]={[id_]=16958977,},},},[ClassName]=ZONE_GROUP,},[Engaged]=true,[RadioName]=Axeman,[Id]=2,[Frequency]=287100000,[GroupName]=GROUP_DYN_B_Center#001,[ClassName]=GROUP,[Callsign]=Axeman 2,},})

INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\Administrateur\Saved Games\DCS.openbeta\/scripts/misFaily/InitMisFaily.lua"]:500: attempt to index local 'tmpCoord' (a nil value)

**Comment by Kalbuth** [comment]
f7e7e10 fixed it.
