### ISSUE TITLE
InitMisFaily.lua"]:949: attempt to call method '?'

### ISSUE THREAD

**Issue by xvx45** [Kalbuth/misFaily#11]
Arrive une fois durant le lancement de la mission. Ci dessous la séquence qui la précède et l'erreur en logs :

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

INFO    SCRIPTING: E:          SET_STATIC03690({[1]=Adding Object:,[2]=TEMPLATE_SLING_3000_cont,})
INFO    SCRIPTING: E:          SET_STATIC03690({[1]=Adding Object:,[2]=TEMPLATE_SLING_1500_sling,})
INFO    SCRIPTING: E:          SET_STATIC03690({[1]=Adding Object:,[2]=TEMPLATE_SLING_3000,})
INFO    SCRIPTING: E:          SET_STATIC03690({[1]=Adding Object:,[2]=TEMPLATE_SLING_1500,})
ERROR   DCS: Mission script error: : [string "/scripts/misFaily/InitMisFaily.lua"]:949: attempt to call method '?' (a nil value)

**Comment by xvx45** [comment]
stack traceback:
	[C]: in function '?'
	[string "scripts/misFaily/InitMisFaily.lua"]:949: in main chunk
	[C]: in function 'dofile'
	[string "local FailyLfs = require('lfs')..."]:2: in main chunk


Dans MissionScripting.lua on a bien "--	sanitizeModule('lfs')"

**Comment by Kalbuth** [comment]
Erreur vue, ca casse la persistence des groupes déployés.
