### ISSUE TITLE
Les Crates ne disparaissent pas lors du chargement

### ISSUE THREAD

**Issue by Kalbuth** [Kalbuth/misFaily#6]
Bug DCS, en MP, utiliser :Destroy() sur un objet de type caisse en elingue fait bien disparaitre l'objet de la simulation, mais le modele 3D reste visible coté clients.
Fix : remplacer par des caisses sans elingue

**Comment by xvx45** [comment]
Je dois retester mais il me semble avoir chargé 2 fois la même caisse (après resawn joueur); cad 
=> Spawn
-> Spawn crate et chargement
-> déchargement et conversion
-> respawn
-> Chargement crate sans respawn.

Testé avec model de crate 3T (sans élingue visible), non testé sur crate 1.5T
Je retest et valide

**Comment by Kalbuth** [comment]
Fixed. Commit 8b0769e

**Comment by xvx45** [comment]
Je rencontre toujours le pb sur la v8, les caisses spawnées et chargées restent. Idem à la transformarion
